In [93]:
import pandas as pd

In [94]:
df = pd.read_csv('Training.csv')

In [95]:
df.head()

,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis,Unnamed: 133
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,Fungal infection,NaN

In [96]:
df.shape

(4920, 134)

In [97]:
df.iloc[:,130:].isnull().sum()

red_sore_around_nose       0
yellow_crust_ooze          0
prognosis                  0
Unnamed: 133            4920
dtype: int64

In [98]:
df.isnull().sum().sum()

np.int64(4920)

In [99]:
df = df.drop('Unnamed: 133',axis=1)

In [100]:
df.dtypes.value_counts()

int64     132
object      1
Name: count, dtype: int64

In [101]:
df = df.drop_duplicates()

In [102]:
df.shape

(304, 133)

In [103]:
df.iloc[:,80:]

,muscle_weakness,stiff_neck,swelling_joints,movement_stiffness,spinning_movements,loss_of_balance,unsteadiness,weakness_of_one_body_side,loss_of_smell,bladder_discomfort,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
403,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,1,Impetigo
405,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,1,Impetigo
406,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,Impetigo
407,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,Impetigo

In [104]:
X = df.drop('prognosis',axis=1)
y = df['prognosis']

In [105]:
y.value_counts()

prognosis
Hepatitis D                                10
Dengue                                     10
Chicken pox                                10
Migraine                                   10
Hepatitis B                                 9
Hypoglycemia                                9
Common Cold                                 9
Tuberculosis                                9
Hepatitis E                                 9
hepatitis A                                 9
Typhoid                                     9
Hyperthyroidism                             9
Jaundice                                    9
Diabetes                                    9
Pneumonia                                   9
Varicose veins                              8
Malaria                                     8
Hypothyroidism                              8
Alcoholic hepatitis                         8
Chronic cholestasis                         8
Osteoarthristis                             7
Bronchial Asthma                            7
(vertigo) Paroymsal  Positional Vertigo     7
Hepatitis C                                 7
Peptic ulcer diseae                         7
Psoriasis                                   7
GERD                                        7
Arthritis                                   6
Impetigo                                    6
Dimorphic hemmorhoids(piles)                6
Cervical spondylosis                        6
Hypertension                                6
Drug Reaction                               6
Heart attack                                5
Allergy                                     5
Paralysis (brain hemorrhage)                5
Gastroenteritis                             5
AIDS                                        5
Acne                                        5
Urinary tract infection                     5
Fungal infection                            5
Name: count, dtype: int64

In [106]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [107]:
y_train.nunique()

41

In [108]:
y_test.nunique()

41

In [109]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, classification_report

lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
y_pred_train = lr.predict(X_train)

print('train evalution')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train, average='weighted'))
print(recall_score(y_train, y_pred_train, average='weighted'))
# print(classification_report(y_train, y_pred_train))

print('test evalution')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted'))
print(recall_score(y_test, y_pred, average='weighted'))
# print(classification_report(y_test, y_pred))

train evalution
1.0
1.0
1.0
test evalution
1.0
1.0
1.0

In [113]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=101, max_depth=3)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
y_pred_train = rf.predict(X_train)

print('train evalution')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train, average='weighted', zero_division=0))
print(recall_score(y_train, y_pred_train, average='weighted'))
# print(classification_report(y_train, y_pred_train))

print('test evalution')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted', zero_division=0))
print(recall_score(y_test, y_pred, average='weighted'))
# print(classification_report(y_test, y_pred))

train evalution
0.8148148148148148
0.7804887975619683
0.8148148148148148
test evalution
0.819672131147541
0.766120218579235
0.819672131147541

In [122]:
from sklearn.naive_bayes import CategoricalNB

naive = CategoricalNB()
naive.fit(X_train, y_train)
y_pred = naive.predict(X_test)
y_pred_train = naive.predict(X_train)

print('train evalution')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train, average='weighted', zero_division=0))
print(precision_score(y_train, y_pred_train, average='macro', zero_division=0))
print(recall_score(y_train, y_pred_train, average='weighted'))
# print(classification_report(y_train, y_pred_train))

print('test evalution')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted', zero_division=0))
print(precision_score(y_test, y_pred, average='macro', zero_division=0))
print(recall_score(y_test, y_pred, average='weighted'))
# print(classification_report(y_test, y_pred))

train evalution
0.9876543209876543
0.9902998236331569
0.9904181184668991
0.9876543209876543
test evalution
0.9672131147540983
0.9644808743169399
0.9552845528455284
0.9672131147540983

In [123]:
from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_pred_train = svc.predict(X_train)

print('train evalution')
print(accuracy_score(y_train, y_pred_train))
print(precision_score(y_train, y_pred_train, average='weighted', zero_division=0))
print(recall_score(y_train, y_pred_train, average='weighted'))
# print(classification_report(y_train, y_pred_train))

print('test evalution')
print(accuracy_score(y_test, y_pred))
print(precision_score(y_test, y_pred, average='weighted', zero_division=0))
print(recall_score(y_test, y_pred, average='weighted'))
# print(classification_report(y_test, y_pred))

train evalution
1.0
1.0
1.0
test evalution
1.0
1.0
1.0

In [124]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)
scores = cross_val_score(
    rf,
    X,
    y,
    cv=cv,
    scoring='f1_macro'
)

print(scores)
print(scores.mean())

[0.67804878 0.77038328 0.68414634 0.64870658 0.72357724]
0.7009724421919543