In [221]:
import pandas as pd

In [222]:
df = pd.read_csv('DateFruit_Dataset.csv')

In [223]:
df.shape

(898, 35)

In [224]:
df = df.drop_duplicates()

In [225]:
df.describe()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,8.980000e+02,8.980000e+02,8.980000e+02,898.000000,898.000000,898.000000
mean,298295.207127,2057.660953,750.811994,495.872785,0.737468,604.577938,0.981840,303845.592428,0.736267,2.131102,...,0.250518,4.247845,5.110894,3.780928,-3.185021e+10,-2.901860e+10,-2.771876e+10,50.082888,48.805681,48.098393
std,107245.205337,410.012459,144.059326,114.268917,0.088727,119.593888,0.018157,108815.656947,0.053745,17.820778,...,0.632918,2.892357,3.745463,2.049831,2.037241e+10,1.712952e+10,1.484137e+10,16.063125,14.125911,10.813862
min,1987.000000,911.828000,336.722700,2.283200,0.344800,50.298400,0.836600,2257.000000,0.512300,1.065300,...,-1.029100,1.708200,1.607600,1.767200,-1.091224e+11,-9.261697e+10,-8.747177e+10,15.191100,20.524700,22.130000
25%,206948.000000,1726.091500,641.068650,404.684375,0.685625,513.317075,0.978825,210022.750000,0.705875,1.373725,...,-0.196950,2.536625,2.508850,2.577275,-4.429444e+10,-3.894638e+10,-3.564534e+10,38.224425,38.654525,39.250725
50%,319833.000000,2196.345450,791.363400,495.054850,0.754700,638.140950,0.987300,327207.000000,0.746950,1.524150,...,0.135550,3.069800,3.127800,3.080700,-2.826156e+10,-2.620990e+10,-2.392928e+10,53.841300,50.337800,49.614100
75%,382573.000000,2389.716575,858.633750,589.031700,0.802150,697.930525,0.991800,388804.000000,0.775850,1.674750,...,0.593950,4.449850,7.320400,4.283125,-1.460482e+10,-1.433105e+10,-1.660367e+10,63.063350,59.573600,56.666675
max,546063.000000,2811.997100,1222.723000,766.453600,1.000000,833.827900,0.997400,552598.000000,0.856200,535.525700,...,3.092300,26.171100,26.736700,32.249500,-1.627316e+08,-5.627727e+08,-4.370435e+08,79.828900,83.064900,74.104600

In [226]:
df.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [227]:
df['Class'].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [228]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [229]:
X = df.drop('Class',axis=1)
y = df['Class']

In [230]:
y.value_counts()

Class
DOKOL     204
SAFAVI    199
ROTANA    166
DEGLET     98
SOGAY      94
IRAQI      72
BERHI      65
Name: count, dtype: int64

In [231]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [232]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [233]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [234]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train_scale = ss.fit_transform(X_train)
X_test_scale = ss.transform(X_test)

In [235]:
import torch
import torch.nn as nn

In [236]:
X_train_tensor = torch.tensor(X_train_scale, dtype = torch.float32)
y_train_tensor = torch.tensor(y_train, dtype = torch.long)
X_test_tensor = torch.tensor(X_test_scale, dtype = torch.float32)
y_test_tensor = torch.tensor(y_test, dtype = torch.long)

In [237]:
y_test_tensor.shape

torch.Size([180])

In [238]:
X_test_tensor.shape

torch.Size([180, 34])

In [239]:
from torch.utils.data import DataLoader, TensorDataset

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [240]:
type(train_dataset)

torch.utils.data.dataset.TensorDataset

In [241]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

In [242]:
type(train_loader)

torch.utils.data.dataloader.DataLoader

In [243]:
num_classes = len(le.classes_)

print(num_classes)
print(le.classes_)

7
['BERHI' 'DEGLET' 'DOKOL' 'IRAQI' 'ROTANA' 'SAFAVI' 'SOGAY']

In [244]:
class ANN(nn.Module):
    def __init__(self, input_size, num_classes):
        super(ANN, self).__init__()

        self.model = nn.Sequential(

            nn.Linear(input_size, 20),
            nn.ReLU(),

            nn.Linear(20, 20),
            nn.ReLU(),

            nn.Linear(20, num_classes)
            
        )

    def forward(self, x):
        return self.model(x)

In [245]:
model = ANN(
    input_size=X_train_tensor.shape[1],
    num_classes=num_classes
)

In [246]:
import torch.optim as optim

criterian = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [248]:
epochs = 50
train_loss = []
val_loss = []

for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()

        outputs = model(xb)
        loss = criterian(outputs, yb)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    epoch_train_loss = running_loss/len(train_loader)
    train_loss.append(epoch_train_loss)

    # print(f"{epoch+1/epochs} loss =>>>> {train_loss}")

    model.eval()
    running_val_loss = 0.0

    with torch.no_grad():
        for xb, yb in test_loader:
            outputs = model(xb)
            loss = criterian(outputs, yb)

            running_val_loss += loss.item()

        epoch_val_loss = running_val_loss/ len(test_loader)
        val_loss.append(epoch_val_loss)



        print(
        f"Epoch {epoch+1}/{epochs} | "
        f"Training Loss: {epoch_train_loss:.4f} | "
        f"Validation Loss: {epoch_val_loss:.4f}"
    )

Epoch 1/50 | Training Loss: 0.1524 | Validation Loss: 0.2211
Epoch 2/50 | Training Loss: 0.1447 | Validation Loss: 0.2212
Epoch 3/50 | Training Loss: 0.1407 | Validation Loss: 0.2160
Epoch 4/50 | Training Loss: 0.1402 | Validation Loss: 0.2228
Epoch 5/50 | Training Loss: 0.1420 | Validation Loss: 0.2180
Epoch 6/50 | Training Loss: 0.1356 | Validation Loss: 0.2188
Epoch 7/50 | Training Loss: 0.1362 | Validation Loss: 0.2221
Epoch 8/50 | Training Loss: 0.1315 | Validation Loss: 0.2174
Epoch 9/50 | Training Loss: 0.1323 | Validation Loss: 0.2187
Epoch 10/50 | Training Loss: 0.1357 | Validation Loss: 0.2203
Epoch 11/50 | Training Loss: 0.1291 | Validation Loss: 0.2181
Epoch 12/50 | Training Loss: 0.1303 | Validation Loss: 0.2170
Epoch 13/50 | Training Loss: 0.1232 | Validation Loss: 0.2197
Epoch 14/50 | Training Loss: 0.1208 | Validation Loss: 0.2202
Epoch 15/50 | Training Loss: 0.1277 | Validation Loss: 0.2161
Epoch 16/50 | Training Loss: 0.1188 | Validation Loss: 0.2174
Epoch 17/50 | Training Loss: 0.1182 | Validation Loss: 0.2195
Epoch 18/50 | Training Loss: 0.1166 | Validation Loss: 0.2192
Epoch 19/50 | Training Loss: 0.1141 | Validation Loss: 0.2184
Epoch 20/50 | Training Loss: 0.1126 | Validation Loss: 0.2189
Epoch 21/50 | Training Loss: 0.1096 | Validation Loss: 0.2177
Epoch 22/50 | Training Loss: 0.1105 | Validation Loss: 0.2192
Epoch 23/50 | Training Loss: 0.1109 | Validation Loss: 0.2202
Epoch 24/50 | Training Loss: 0.1168 | Validation Loss: 0.2167
Epoch 25/50 | Training Loss: 0.1170 | Validation Loss: 0.2195
Epoch 26/50 | Training Loss: 0.1065 | Validation Loss: 0.2231
Epoch 27/50 | Training Loss: 0.1049 | Validation Loss: 0.2212
Epoch 28/50 | Training Loss: 0.1045 | Validation Loss: 0.2219
Epoch 29/50 | Training Loss: 0.1039 | Validation Loss: 0.2202
Epoch 30/50 | Training Loss: 0.1029 | Validation Loss: 0.2207
Epoch 31/50 | Training Loss: 0.1011 | Validation Loss: 0.2207
Epoch 32/50 | Training Loss: 0.1008 | Validation Loss: 0.2208
Epoch 33/50 | Training Loss: 0.0990 | Validation Loss: 0.2199
Epoch 34/50 | Training Loss: 0.0926 | Validation Loss: 0.2187
Epoch 35/50 | Training Loss: 0.0941 | Validation Loss: 0.2190
Epoch 36/50 | Training Loss: 0.0918 | Validation Loss: 0.2225
Epoch 37/50 | Training Loss: 0.0922 | Validation Loss: 0.2182
Epoch 38/50 | Training Loss: 0.0956 | Validation Loss: 0.2195
Epoch 39/50 | Training Loss: 0.0901 | Validation Loss: 0.2210
Epoch 40/50 | Training Loss: 0.0904 | Validation Loss: 0.2214
Epoch 41/50 | Training Loss: 0.0905 | Validation Loss: 0.2267
Epoch 42/50 | Training Loss: 0.0918 | Validation Loss: 0.2196
Epoch 43/50 | Training Loss: 0.0850 | Validation Loss: 0.2221
Epoch 44/50 | Training Loss: 0.0856 | Validation Loss: 0.2236
Epoch 45/50 | Training Loss: 0.0869 | Validation Loss: 0.2218
Epoch 46/50 | Training Loss: 0.0838 | Validation Loss: 0.2249
Epoch 47/50 | Training Loss: 0.0804 | Validation Loss: 0.2239
Epoch 48/50 | Training Loss: 0.0814 | Validation Loss: 0.2249
Epoch 49/50 | Training Loss: 0.0805 | Validation Loss: 0.2245
Epoch 50/50 | Training Loss: 0.0777 | Validation Loss: 0.2233

In [252]:
correct =0
total =0


model.eval()

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb)
         # [0.2, 0.5, 1.3, -0.5, ..] - 7 vals
        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct/total * 100)

accuracy:  93.88888888888889