In [76]:
import pandas as pd

In [77]:
df = pd.read_csv('Energy_consumption.csv')

In [78]:
df.shape

(1000, 11)

In [79]:
df = df.drop_duplicates()

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Timestamp          1000 non-null   object
 1   Temperature        1000 non-null   float64
 2   Humidity           1000 non-null   float64
 3   SquareFootage      1000 non-null   float64
 4   Occupancy          1000 non-null   int64
 5   HVACUsage          1000 non-null   object
 6   LightingUsage      1000 non-null   object
 7   RenewableEnergy    1000 non-null   float64
 8   DayOfWeek          1000 non-null   object
 9   Holiday            1000 non-null   object
 10  EnergyConsumption  1000 non-null   float64
dtypes: float64(5), int64(1), object(5)
memory usage: 86.1+ KB

In [81]:
df.head()

,Timestamp,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption
0,2022-01-01 00:00:00,25.139433,43.431581,1565.693999,5,On,Off,2.774699,Monday,No,75.364373
1,2022-01-01 01:00:00,27.731651,54.225919,1411.064918,1,On,On,21.831384,Saturday,No,83.401855
2,2022-01-01 02:00:00,28.704277,58.907658,1755.715009,2,Off,Off,6.764672,Sunday,No,78.270888
3,2022-01-01 03:00:00,20.080469,50.371637,1452.316318,1,Off,On,8.623447,Wednesday,No,56.519850
4,2022-01-01 04:00:00,23.097359,51.401421,1094.130359,9,On,Off,3.071969,Friday,No,70.811732

In [82]:
df.describe()

,Temperature,Humidity,SquareFootage,Occupancy,RenewableEnergy,EnergyConsumption
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,24.982026,45.395412,1500.052488,4.581000,15.132813,77.055873
std,2.836850,8.518905,288.418873,2.865598,8.745917,8.144112
min,20.007565,30.015975,1000.512661,0.000000,0.006642,53.263278
25%,22.645070,38.297722,1247.108548,2.000000,7.628385,71.544690
50%,24.751637,45.972116,1507.967426,5.000000,15.072296,76.943696
75%,27.418174,52.420066,1740.340165,7.000000,22.884064,82.921742
max,29.998671,59.969085,1999.982252,9.000000,29.965327,99.201120

In [83]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

df['Year'] = df['Timestamp'].dt.year
df['Month'] = df['Timestamp'].dt.month
df['Day'] = df['Timestamp'].dt.day

df = df.drop('Timestamp',axis=1)

In [84]:
df.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption,Year,Month,Day
0,25.139433,43.431581,1565.693999,5,On,Off,2.774699,Monday,No,75.364373,2022,1,1
1,27.731651,54.225919,1411.064918,1,On,On,21.831384,Saturday,No,83.401855,2022,1,1
2,28.704277,58.907658,1755.715009,2,Off,Off,6.764672,Sunday,No,78.270888,2022,1,1
3,20.080469,50.371637,1452.316318,1,Off,On,8.623447,Wednesday,No,56.519850,2022,1,1
4,23.097359,51.401421,1094.130359,9,On,Off,3.071969,Friday,No,70.811732,2022,1,1

In [85]:
df['HVACUsage'] = df['HVACUsage'].map({'On': 1,'Off': 0})
df['LightingUsage'] = df['LightingUsage'].map({'On': 1,'Off': 0})
df['Holiday'] = df['Holiday'].map({'Yes': 1,'No': 0})

In [86]:
df['Holiday'].unique()

array([0, 1])

In [87]:
df.head()

,Temperature,Humidity,SquareFootage,Occupancy,HVACUsage,LightingUsage,RenewableEnergy,DayOfWeek,Holiday,EnergyConsumption,Year,Month,Day
0,25.139433,43.431581,1565.693999,5,1,0,2.774699,Monday,0,75.364373,2022,1,1
1,27.731651,54.225919,1411.064918,1,1,1,21.831384,Saturday,0,83.401855,2022,1,1
2,28.704277,58.907658,1755.715009,2,0,0,6.764672,Sunday,0,78.270888,2022,1,1
3,20.080469,50.371637,1452.316318,1,0,1,8.623447,Wednesday,0,56.519850,2022,1,1
4,23.097359,51.401421,1094.130359,9,1,0,3.071969,Friday,0,70.811732,2022,1,1

In [88]:
df['HVACUsage'].unique()

array([1, 0])

In [89]:
df.isnull().sum()

Temperature          0
Humidity             0
SquareFootage        0
Occupancy            0
HVACUsage            0
LightingUsage        0
RenewableEnergy      0
DayOfWeek            0
Holiday              0
EnergyConsumption    0
Year                 0
Month                0
Day                  0
dtype: int64

In [90]:
X = df.drop('EnergyConsumption',axis=1)
y = df['EnergyConsumption']

In [91]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

scale_col = ['Temperature','Humidity','SquareFootage','RenewableEnergy']
encode_col = ['DayOfWeek']

preprocess = ColumnTransformer(transformers=[
    ('ss', StandardScaler(), scale_col),
    ('encode', OneHotEncoder(handle_unknown='ignore', drop='first', sparse_output=False), encode_col)
], remainder='passthrough')

In [93]:
X_train_pre = preprocess.fit_transform(X_train)
X_test_pre = preprocess.transform(X_test)

In [96]:
X_train_pre.shape

(800, 17)

In [98]:
X_train_pre

array([[-6.00071228e-01,  1.17232328e-01,  5.10638984e-01, ...,
         2.02200000e+03,  1.00000000e+00,  2.00000000e+00],
       [-1.01407377e+00, -1.36885500e+00,  1.71124264e+00, ...,
         2.02200000e+03,  1.00000000e+00,  2.30000000e+01],
       [ 4.15776383e-01, -2.42279219e-01,  2.55738630e-01, ...,
         2.02200000e+03,  1.00000000e+00,  2.90000000e+01],
       ...,
       [ 7.20718834e-01,  1.37928000e+00, -1.24606223e+00, ...,
         2.02200000e+03,  2.00000000e+00,  5.00000000e+00],
       [ 1.49491710e+00, -4.34894496e-01, -1.73591951e+00, ...,
         2.02200000e+03,  1.00000000e+00,  1.90000000e+01],
       [-1.43939087e+00, -6.92705581e-01,  2.43546382e-01, ...,
         2.02200000e+03,  1.00000000e+00,  5.00000000e+00]],
      shape=(800, 17))

In [99]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

lr = LinearRegression()
lr.fit(X_train_pre, y_train)
y_pred = lr.predict(X_test_pre)
y_pred_train = lr.predict(X_train_pre)

print('train')
print(root_mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train))

print('test')

print(root_mean_squared_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

train
4.984083838047772
24.841091704689006
24.841091704689006
0.6261692479635967
test
5.159732682641507
26.622841356318922
4.113793162630194
0.5935436344254752

In [104]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=101, max_depth=3, min_samples_leaf=5)
rf.fit(X_train_pre, y_train)
y_pred = rf.predict(X_test_pre)
y_pred_train = rf.predict(X_train_pre)

print('train')
print(root_mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train))

print('test')

print(root_mean_squared_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

train
5.20940936219957
27.137945902972525
27.137945902972525
0.5916041514505389
test
5.541417744740354
30.707310621723273
4.3714129616531885
0.5311852065365203

In [104]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

rf = RandomForestRegressor()

param = [{
    'n_estimators':[51,101,201,301]
    'max_depth':[2,3,4] 
    'min_samples_leaf':[4,5,6]
}]
grid = GridSearchCV(estimator=rf, param_grid=param, cv=5, n_jobs=)
rf.fit(X_train_pre, y_train)
y_pred = rf.predict(X_test_pre)
y_pred_train = rf.predict(X_train_pre)

print('train')
print(root_mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train))

print('test')

print(root_mean_squared_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

train
5.20940936219957
27.137945902972525
27.137945902972525
0.5916041514505389
test
5.541417744740354
30.707310621723273
4.3714129616531885
0.5311852065365203

In [101]:
from sklearn.neighbors import KNeighborsRegressor

knn = KNeighborsRegressor()
knn.fit(X_train_pre, y_train)
y_pred = knn.predict(X_test_pre)
y_pred_train = knn.predict(X_train_pre)

print('train')
print(root_mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train))

print('test')

print(root_mean_squared_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

train
5.106352128599696
26.074832061254643
26.074832061254643
0.6076028302394703
test
6.608350513384534
43.67029650774963
5.407068505232164
0.3332766490046787

In [100]:
from sklearn.svm import SVR

svr = SVR()
svr.fit(X_train_pre, y_train)
y_pred = svr.predict(X_test_pre)
y_pred_train = svr.predict(X_train_pre)

print('train')
print(root_mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(mean_squared_error(y_train, y_pred_train))
print(r2_score(y_train, y_pred_train))

print('test')

print(root_mean_squared_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(mean_absolute_error(y_test, y_pred))
print(r2_score(y_test, y_pred))

train
8.15449373718961
66.49576810986457
66.49576810986457
-0.0006872200007506102
test
8.096950005519155
65.56059939187665
6.583925624004328
-0.0009270835167562996